### ISSUE TITLE
License Please?

### ISSUE THREAD

**Issue by heathermeeker** [avs333/Nougat_dlfunctions#2]
Thanks for posting this code.  Could you please add a license (preferably MIT or BSD)?

**Comment by avs333** [comment]
Oh. I believe it's just a tiny hack (160 lines of code or so, those license files seem to be much larger...). It's free for use by anyone. The same applies to any other code in my repositories.

**Comment by heathermeeker** [comment]
Thank you!

**Comment by orktes** [comment]
Hi! Thanks for making this freely available! I definitely understand and respect your reasoning for not adding the LICENSE file. But just to be able to list it under our 3rd party / vendor license docs could you verify that this is for example MIT (or even public domain) by just stating it here.

Just a simple "Yes it's under MIT License" will do :)

**Comment by avs333** [comment]
No prob, added it!
