### ISSUE TITLE
got " error: arithmetic on a pointer to void" after modify fake_dlfcn.c to fake_dlfcn.cpp

### ISSUE THREAD

**Issue by muyiou** [avs333/Nougat_dlfunctions#4]
shoff = ((void *) elf) + elf->e_shoff;
Error:(97, 28) error: arithmetic on a pointer to void

**Comment by avs333** [comment]
You're probably compiling with clang++ (it's the default NDK_TOOLCHAIN_VERSION since some ndk release). Either set it to e.g. "4.9" in Application.mk and specify "-Wno-pointer-arith" in cflags, or typecast "elf" to char* rather than void* and the whole sum to void* again.
